package pl.kalat.gprogmanstarter.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import pl.kalat.gprogmanstarter.implementation.ArrayItem;
import pl.kalat.gprogmanstarter.implementation.ListApps;
import pl.kalat.gprogmanstarter.implementation.PathConfigFile;

/**
 *
 * @author Robert Kałat
 */
public class gProgmanStarter extends javax.swing.JFrame {

    /**
     * Creates new form gProgmanStarter
     */
    public gProgmanStarter(String appName) {
        initComponents();

        /**
         * create combobox with available DB
         */
        arrayItem = ArrayItem.prepareArrayItem("gProgmanStarter.config.ini");
        for (int i = 0; i < arrayItem.length; i++) {
            jComboBoxDB.addItem(arrayItem[i][0]);
        }
        this.appName = appName.toLowerCase();
        this.appExe = ListApps.getNameExe(appName);
        this.appConfig = ListApps.getNameConfig(appName);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxDB = new javax.swing.JComboBox<>();
        jButtonEnd = new javax.swing.JButton();
        jButtonRun = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Baza: ");

        jComboBoxDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDBActionPerformed(evt);
            }
        });

        jButtonEnd.setText("Koniec");
        jButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEndActionPerformed(evt);
            }
        });

        jButtonRun.setText("Uruchom");
        jButtonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRunActionPerformed(evt);
            }
        });

        jLabel2.setText("Wybierz baze z listy z którą chcesz uruchomić program");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setText("Wolters Kluwer Polska Sp. z o.o.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRun)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEnd))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDB, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnd)
                    .addComponent(jButtonRun))
                .addGap(14, 14, 14)
                .addComponent(jLabel3))
        );

        setSize(new java.awt.Dimension(416, 154));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEndActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonEndActionPerformed

    private void jButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRunActionPerformed

        /**
         * prepare Config
         */
        String companySelected = jComboBoxDB.getSelectedItem().toString();
        String appConfigSelected = "";
        int i = 0;
        while (i < arrayItem.length) {
            if (arrayItem[i][0].equals(companySelected)) {
                appConfigSelected = arrayItem[i][1];
            }
            i++;
        }

        try {
            PathConfigFile.configFileCopy(appName, appConfig, appConfigSelected);
        } catch (IOException ex) {
            Logger.getLogger(gProgmanStarter.class.getName()).log(Level.SEVERE, null, ex);
        }
       

        /**
         * Run application
         */
        Runtime r = Runtime.getRuntime();
        try {
            r.exec(appExe);
        } catch (IOException ex) {
            Logger.getLogger(gProgmanStarter.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonRunActionPerformed

    private void jComboBoxDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDBActionPerformed

    private String[][] arrayItem;
    private String appName;
    private String appExe;
    private String appConfig;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnd;
    private javax.swing.JButton jButtonRun;
    private javax.swing.JComboBox<String> jComboBoxDB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
